name: Validador de Dependencias

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Garante que está na branch do PR

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Removi a linha do cache: 'npm' para evitar que ele trave se não achar o lockfile de cara

      - name: Instalar Dependências
        run: npm install

      - name: Validar Segurança
        run: npm audit --audit-level=moderate